### ISSUE TITLE
Diagnose Greengrass issues

### ISSUE THREAD

**Issue by timmattison** [awslabs/aws-greengrass-provisioner#147]
Connectivity: If the GGC has too many IPs it will report in the logs that it can not update the connectivity info. There needs to be a mechanism to query the group and determine if this is happening.

Dependencies: If NodeJS or Python or Java symlinks aren't set properly the system will not be able to run functions in those languages.

Functions failing: If a function takes too long to process a message it will be killed and restarted.

**Comment by timmattison** [comment]
Error messages:

Connectivity (in GGIPDetector.log):
```
Too many items in the Connectivity Information list. You can store a maximum of 10 endpoints.
```

Dependencies (in runtime.log):

```
unable to create worker process for arn:aws:lambda:us-east-1:xxx:function:zzz-bbb:8. cannot find executable nodejs8.10 under any of the provided paths [/usr/bin /usr/local/bin]
```

Functions failing (in runtime.log):

```
WorkItem reached max retry limit.    {"invocationId": "d716f4a1-edc5-4d44-6b00-e0aad3cea516", "funcArn": "arn:aws:lambda:us-east-1:xxx:function:vvv-bbb:26", "workerId": "5f48db91-2729-4acb-432a-f9b01d0de00e"}
```

**Comment by timmattison** [comment]
1, 2, and 3 implemented.

**Comment by jadonk** [comment]
Why is Greengrass so braindead?
