### ISSUE TITLE
Error when trying to deploy to new group

### ISSUE THREAD

**Issue by rithik** [awslabs/aws-greengrass-provisioner#168]
I'm trying to use the provisioner to create a new group with the Python Hello World Lambda. However, I keep getting the following error: ```[ERROR] AwsGreengrassProvisioner: ..\aws-greengrass-lambda-functions\deployments\python-hello-world.conf: 1: No configuration setting found for key 'conf.core'```

I ran the following command to get that error ```java -jar build/libs/AwsGreengrassProvisioner.jar -g TestGroup2 -a X86_64 -d ../aws-greengrass-lambda-functions/deployments/python-hello-world.conf --script```

I have successfully built the jar file (according to the repo's main readme).

I tried deleting all of my files and re-cloning the repo and still get this issue. Any advice on fixing this issue would be greatly appreciated!

**Comment by timmattison** [comment]
Testing this now.

**Comment by timmattison** [comment]
Reproduced. This is because the provisioner is looking for the deployments/deployment.defaults.conf file. When it can't find this it reports that error.

Can you try running it from the `aws-greengrass-lambda-functions` directory?

Probably like this in your case this would work:

```
cd ../aws-greengrass-lambda-functions
java -jar ../aws-greengrass-provisioner/build/libs/AwsGreengrassProvisioner.jar -g TestGroup2 -a X86_64 -d deployments/python-hello-world.conf --script
```

**Comment by rithik** [comment]
That worked! Thank you!

**Comment by timmattison** [comment]
👍
