### ISSUE TITLE
Support for shadow sync

### ISSUE THREAD

**Issue by QuinnCiccoretti** [awslabs/aws-greengrass-provisioner#177]
Currently, [this code](https://github.com/awslabs/aws-greengrass-provisioner/blob/3185951190dc5918bdd515dbbf4b88ee46b71116/src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java#L189) sets the core shadow sync to false. There does not appear to be any way to specify other options. Perhaps this could be a command line argument? Or the provisioner could read in some sort of configuration file.

**Comment by timmattison** [comment]
I know this can be done for Greengrass devices, but I think you're right about this. Are you planning on storing state in the group's main shadow?

**Comment by QuinnCiccoretti** [comment]
I'm interested in setting the shadow of the Greengrass Core, not necessarily connected devices. I was planning on using the core shadow for some of the docker work I'm doing. I don't really need a shadow of the group, just the Core's shadow.

**Comment by timmattison** [comment]
Oops, didn't mean to close this. Let me know if the new default works for you. Then I'll close this.

**Comment by timmattison** [comment]
I actually implemented this in another commit. I'm running integration tests now.

**Comment by QuinnCiccoretti** [comment]
Works great with the docker code I was working on. Thanks!
