### ISSUE TITLE
Provisioner deletes lambda and updates version rather than update latest alias

### ISSUE THREAD

**Issue by QuinnCiccoretti** [awslabs/aws-greengrass-provisioner#262]
It seems like it would be better to keep older versions of the lambda. You could create a new version of the lambda, and then update the latest alias. This would make development easier and make deployment easier.

**Comment by timmattison** [comment]
This was developed a while ago. I'll take a look again. It sounds like the behavior may have been part of an early design choice that no longer applies. Thanks!

**Comment by timmattison** [comment]
Looks like this was done to make updates easier since I don't have to worry about previous versions. Looking into it.

**Comment by timmattison** [comment]
@QuinnCiccoretti I think this does it but I'm out of time to test today. Any chance you could kick the tires on this branch and let me know if it works as expected?

**Comment by QuinnCiccoretti** [comment]
@cea2aj
