### ISSUE TITLE
How to prevent sub-directory in function not to be disappeared?

### ISSUE THREAD

**Issue by yunchancho** [awslabs/aws-greengrass-provisioner#450]
As I checked in AWS console, I found that sub-directory in function is disappeared after uploading it from my local pc using GGP. And all files in the sub-directory are placed on top-level directory of lambda. 

Is this intended behavior? or Bug? 
How do I avoid this issue?

**Comment by timmattison** [comment]
Is this a sub directory that contains data or some configuration? Could you include a tree that shows what the file system looks like before it is built and what shows up in Lambda?

**Comment by yunchancho** [comment]
This is files which are in my local pc and uploaded by GGP.

```
.
├── HelloWorldPython3.py
├── README.md
├── function.conf
├── libs
│   ├── __init__.py
│   └── test.py
├── requirements.txt
└── setup.cfg
```

After these uploaded into AWS Lambda using GGP, `libs` directory is appeared and its files(e.g. test.py) are placed in top level directory like this.
This occurs runtime error that `libs` directory is not found.
.
├── HelloWorldPython3.py
├── README.md
├── __init__.py
├── cbor2
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── compat.py
│   ├── compat.pyc
│   ├── decoder.py
│   ├── decoder.pyc
│   ├── encoder.py
│   ├── encoder.pyc
│   ├── types.py
│   └── types.pyc
├── cbor2-4.1.2.dist-info
│   ├── INSTALLER
│   ├── LICENSE.txt
│   ├── METADATA
│   ├── RECORD
│   ├── WHEEL
│   └── top_level.txt
├── function.conf
├── greengrasssdk
│   ├── IoTDataPlane.py
│   ├── IoTDataPlane.pyc
│   ├── Lambda.py
│   ├── Lambda.pyc
│   ├── SecretsManager.py
│   ├── SecretsManager.pyc
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── client.py
│   ├── client.pyc
│   ├── stream_manager
│   └── utils
├── greengrasssdk-1.5.0.dist-info
│   ├── INSTALLER
│   ├── LICENSE
│   ├── METADATA
│   ├── RECORD
│   ├── WHEEL
│   └── top_level.txt
├── requirements.txt
├── setup.cfg
└── test.py
```

This behavior doesn't make sense to me.

**Comment by timmattison** [comment]
I’ll take a look at this on Monday and document what’s happening here. Thanks for the info!

**Comment by yunchancho** [comment]
@timmattison Thanks your investigation for this issue.

**Comment by timmattison** [comment]
Investigating this, and your fix, now. Thank you!

**Comment by timmattison** [comment]
I recreated it and the fix you provided works great, merging now.
