### ISSUE TITLE
Typo in https://github.com/awslabs/aws-greengrass-provisioner/blob/master/docs/GettingStarted.md

### ISSUE THREAD

**Issue by asvand** [awslabs/aws-greengrass-provisioner#454]
In https://github.com/awslabs/aws-greengrass-provisioner/blob/master/docs/GettingStarted.md the example "GGP -a ARM32 -g mytestgroup -d deployments/python-hello-world.conf --script" refers to non-existing file "python-hello-world.conf"

Existing files in deployments:
ARM32SampleC.conf                              embedded-vaadin-skeleton.conf                  latency-dashboard-with-cloudwatch-metrics.conf python3-hello-world.conf
X86_64SampleC.conf                             empty.conf                                     latency-dashboard.conf                         python3-mqtt-client.conf
all-hello-world.conf                           function.defaults.conf                         latency-with-cloudwatch-metrics.conf           python3-raspberry-pi-gpio.conf
benchmark-reuse.conf                           ggd-test.conf                                  lifx.conf                                      python3-secrets-manager.conf
benchmark.conf                                 git-test.conf                                  node-hello-world.conf                          sensehat.conf
cdd-skeleton.conf                              http-node.conf                                 python-basic-ingest-with-cloudformation.conf   socket-server.conf
deployment.defaults.conf                       http-python-and-node.conf                      python-hello-world-with-cloudformation.conf    web-server-node.conf
dmi.conf                                       http-python.conf                               python-only-benchmark.conf
docker.conf                                    java-only-benchmark.conf                       python2-hello-world.conf

**Comment by timmattison** [comment]
Oops, when the function changed from python-* to python2-* I missed this. Thanks, I'll fix it.

**Comment by timmattison** [comment]
OK, the commit is in. Will be merged in a bit.
