### ISSUE TITLE
How to configure setting of logs for cloudwatch and local device

### ISSUE THREAD

**Issue by yunchancho** [awslabs/aws-greengrass-provisioner#509]
Hi, @timmattison 

I wonder the way to configure setting of logs for cloudwatch and local device using GGP. 
Could you let me know if GGP already support it?

Thanks in advance.

**Comment by timmattison** [comment]
I originally didn't need this to be configured specially so it is currently hardcoded to some default values here - https://github.com/awslabs/aws-greengrass-provisioner/blob/a193b43cc278a9f90500bda64036039e8d7b955b/src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicGreengrassHelper.java#L474

What settings do you need to change? I think I could update it to being configurable if necessary.

**Comment by yunchancho** [comment]
I need to change log level or remove itself. Recently I was charged big money from AWS due to cloudwatch. As I checked detail, root cause was log level of Greengrass core. My greengrass core generate some log per 10ms for several reasons. 

So, I would be glad if GGP supports log level to be configurable.

**Comment by timmattison** [comment]
Let me see what I can do. Stay tuned.

**Comment by timmattison** [comment]
I think I've got it. You'll need a new deployment.defaults.conf from the Lambda functions repo. If you don't have it it will use the default config. If you do have a config in defaults, it'll use that. You can set it to an empty array if you want no loggers.

You can also override it in each deployment configuration file if you'd like to keep a default but configure the loggers differently based on your application.

It'll be merged in soon. Just running some tests.

**Comment by yunchancho** [comment]
@timmattison, What you've done was what I need exactly.  `loggers` option of deployment.defaults.conf works perfectly. Huge thanks to you for quick support!! 👍

**Comment by timmattison** [comment]
Excellent! Happy to help. Keep me posted on anything else you need.
