### ISSUE TITLE
Dependencies failing on Debian 9 (Stretch)

### ISSUE THREAD

**Issue by typemismatch** [awslabs/aws-greengrass-provisioner#516]
There are a few dependencies that don't install without errors on Debian 9, throwing a "No module named ‘setuptools’" error message. Should probably be "python-setuptools" etc.

**Comment by timmattison** [comment]
I checked and it does use python-setuptools and python3-setuptools in the current script. Share the logs and I’ll try to track it down. 

Double check that you have the latest script too as that may have changed in the past few months.

**Comment by timmattison** [comment]
I think this isn't an issue anymore but let me know if it is still giving you trouble.
