### ISSUE TITLE
Add support for Greengrass Connectors

### ISSUE THREAD

**Issue by typemismatch** [awslabs/aws-greengrass-provisioner#57]
Add support for connectors, there appears to be a generic structure to the connector configuration. This needs to be a generic conf with a connector ARN and connector params so that you don't have to build something for each connector. All connectors have an ARN, I suspect many more will be coming.

**Comment by timmattison** [comment]
Investigating now.

**Comment by timmattison** [comment]
Making progress. May have this out today.

**Comment by timmattison** [comment]
There's some additional complexity that I want to remove when this is released. The current branch allows a user to specify the parameters necessary to deploy containers but doesn't offer much in the way of checking to make sure things are done correctly.

If this drags more than a week or so I'll release what is here now and then enter a new issue to improve the error handling.
