### ISSUE TITLE
Dependencies fail in Ubuntu 18.x

### ISSUE THREAD

**Issue by typemismatch** [awslabs/aws-greengrass-provisioner#61]
No dependencies get installed, throws a bunch of exceptions and even Python doesn't get installed so the core fails to start.

**Comment by timmattison** [comment]
Can you include the exceptions/logs?

**Comment by timmattison** [comment]
I just tried this on X86-64 18.04 on EC2 in us-east-1 with no issues.

```
$ uname -a
Linux ip-172-31-53-101 4.15.0-1032-aws #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by timmattison** [comment]
Also tried on ARM64 18.04 on EC2 in us-east-1 with no issues.

```
$ uname -a
Linux ip-172-31-8-195 4.15.0-1028-aws #29+nutmeg8-Ubuntu SMP Tue Nov 20 02:59:41 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by timmattison** [comment]
If you find some logs attach them and reopen this.
