### ISSUE TITLE
Docker containers as a Greengrass device

### ISSUE THREAD

**Issue by NickDarvey** [awslabs/aws-greengrass-provisioner#730]
Hullo! Does GGP have any functionality that helps provision a Greengrass device (and its credentials) for my container to interact with MQTT topics as described in the [AWS docs](https://docs.aws.amazon.com/greengrass/latest/developerguide/docker-app-connector.html#docker-app-connector-mqtt-communication)?

I've had a look through this repo and the sample one but couldn't see anything related.

**Comment by timmattison** [comment]
There used to be a feature to provision Greengrass devices but it was removed as it hadn’t been maintained and it wasn’t really used that much. I can revisit that specifically for Docker containers using the connector. If that’s what you are looking for open an issue and we will see what we can do.

**Comment by NickDarvey** [comment]
Yes, specifically for the Docker Connector so my containers can publish messages to/receive messages from MQTT topics

**Comment by NickDarvey** [comment]
See #731
