### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [awslabs/aws-greengrass-provisioner#760]
https://github.com/awslabs/aws-greengrass-provisioner/blob/0cceba71879b5a6d3d26c98e74e8bf1991566a1d/src/main/java/com/awslabs/aws/greengrass/provisioner/implementations/helpers/BasicIoHelper.java#L125

The program can potentially fail to release a system resource.

**Comment by timmattison** [comment]
Thanks!
